/**
 * OpenAPI spec version: 2.0.0
 * Contact: users@acsoftware.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BundleContext } from './bundleContext';
import { DictionaryStringString } from './dictionaryStringString';
import { ServiceReferenceObject } from './serviceReferenceObject';
import { Version } from './version';


export interface Bundle { 
    bundleContext?: BundleContext;
    headers?: DictionaryStringString;
    symbolicName?: string;
    bundleId?: number;
    registeredServices?: Array<ServiceReferenceObject>;
    lastModified?: number;
    servicesInUse?: Array<ServiceReferenceObject>;
    version?: Version;
    location?: string;
    state?: number;
}
