/**
 * OpenAPI spec version: 2.0.0
 * Contact: users@acsoftware.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HDevice } from './hDevice';
import { HPacketField } from './hPacketField';


export interface HPacket { 
    id?: number;
    entityVersion: number;
    readonly entityCreateDate?: Date;
    readonly entityModifyDate?: Date;
    categoryIds?: Array<number>;
    tagIds?: Array<number>;
    name?: string;
    type?: HPacket.TypeEnum;
    format?: HPacket.FormatEnum;
    serialization?: HPacket.SerializationEnum;
    device?: HDevice;
    version?: string;
    fields?: Array<HPacketField>;
    valid?: boolean;
    timestampField?: string;
    timestampFormat?: string;
    unixTimestamp?: boolean;
    unixTimestampFormatSeconds?: boolean;
    trafficPlan?: HPacket.TrafficPlanEnum;
}
export namespace HPacket {
    export type TypeEnum = 'INPUT' | 'OUTPUT' | 'IO';
    export const TypeEnum = {
        INPUT: 'INPUT' as TypeEnum,
        OUTPUT: 'OUTPUT' as TypeEnum,
        IO: 'IO' as TypeEnum
    };
    export type FormatEnum = 'JSON' | 'XML' | 'CSV' | 'TEXT';
    export const FormatEnum = {
        JSON: 'JSON' as FormatEnum,
        XML: 'XML' as FormatEnum,
        CSV: 'CSV' as FormatEnum,
        TEXT: 'TEXT' as FormatEnum
    };
    export type SerializationEnum = 'AVRO' | 'NONE';
    export const SerializationEnum = {
        AVRO: 'AVRO' as SerializationEnum,
        NONE: 'NONE' as SerializationEnum
    };
    export type TrafficPlanEnum = 'LOW' | 'MEDIUM' | 'HIGH' | 'INTENSIVE';
    export const TrafficPlanEnum = {
        LOW: 'LOW' as TrafficPlanEnum,
        MEDIUM: 'MEDIUM' as TrafficPlanEnum,
        HIGH: 'HIGH' as TrafficPlanEnum,
        INTENSIVE: 'INTENSIVE' as TrafficPlanEnum
    };
}
