/**
 * HyperIoT HProject
 * HyperIoT HProject API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: users@acsoftware.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface HProjectSharingInfo { 
    ownerId?: number;
    ownerName?: string;
    ownerLastName?: string;
    collaboratorCounters?: number;
}