import { Component, Inject, OnInit } from '@angular/core';
import { DialogRef } from '../../hyt-dialog/dialog-ref';
import { DIALOG_DATA } from '../../hyt-dialog/dialog-tokens';

@Component({
  selector: 'hyt-icon-picker-list',
  templateUrl: './hyt-icon-picker-list.component.html',
  styleUrls: ['./hyt-icon-picker-list.component.scss']
})
export class HytIconPickerListComponent implements OnInit {

  allIcons: string[] = [];
  filteredIcons: string[] = [];

  filterValue = '';

  hytIconList = [
    "icon-hyt_action",
    "icon-hyt_asterisk",
    "icon-hyt_cancel",
    "icon-hyt_cancelC",
    "icon-hyt_caretDown",
    "icon-hyt_caretUp",
    "icon-hyt_categories",
    "icon-hyt_category",
    "icon-hyt_charCake",
    "icon-hyt_chartBar",
    "icon-hyt_chartGauge",
    "icon-hyt_chartLine",
    "icon-hyt_chartRadar",
    "icon-hyt_chip",
    "icon-hyt_clock",
    "icon-hyt_coins",
    "icon-hyt_dash",
    "icon-hyt_dashPlus",
    "icon-hyt_device",
    "icon-hyt_devicePlus",
    "icon-hyt_download",
    "icon-hyt_duplicate",
    "icon-hyt_enrichments",
    "icon-hyt_enrichmentsPlus",
    "icon-hyt_event",
    "icon-hyt_eventPlus",
    "icon-hyt_exL",
    "icon-hyt_exM",
    "icon-hyt_exS",
    "icon-hyt_eyeClose",
    "icon-hyt_eyeOpen",
    "icon-hyt_fields",
    "icon-hyt_fieldsPlus",
    "icon-hyt_hamClose",
    "icon-hyt_hamOpen",
    "icon-hyt_helpM",
    "icon-hyt_helpS",
    "icon-hyt_home",
    "icon-hyt_info",
    "icon-hyt_join",
    "icon-hyt_layout",
    "icon-hyt_layoutPlus",
    "icon-hyt_less",
    "icon-hyt_lessC",
    "icon-hyt_lessX",
    "icon-hyt_lock",
    "icon-hyt_mail",
    "icon-hyt_map",
    "icon-hyt_notification",
    "icon-hyt_off",
    "icon-hyt_packets",
    "icon-hyt_packetsPlus",
    "icon-hyt_pause",
    "icon-hyt_play",
    "icon-hyt_plus",
    "icon-hyt_plusC",
    "icon-hyt_plusX",
    "icon-hyt_projectRSolo",
    "icon-hyt_projects",
    "icon-hyt_projectSolo",
    "icon-hyt_projectsPlus",
    "icon-hyt_projectsR",
    "icon-hyt_projectsRPlus",
    "icon-hyt_reload",
    "icon-hyt_save",
    "icon-hyt_search",
    "icon-hyt_setting",
    "icon-hyt_sortAlfa",
    "icon-hyt_sortDown",
    "icon-hyt_sortStar",
    "icon-hyt_sortUp",
    "icon-hyt_star",
    "icon-hyt_statistics",
    "icon-hyt_statisticsPlus",
    "icon-hyt_stop",
    "icon-hyt_switch",
    "icon-hyt_tableBig",
    "icon-hyt_tabLight",
    "icon-hyt_tag",
    "icon-hyt_tags",
    "icon-hyt_trash",
    "icon-hyt_user",
    "icon-hyt_userCircle",
    "icon-hyt_userEx",
    "icon-hyt_valid",
    "icon-hyt_warnC",
    "icon-hyt_warnT",
    "icon-hyt_widget",
    "icon-hyt_widgetPlus",
    "icon-hyt_wifiOff",
    "icon-hyt_wifiOffFilled",
    "icon-hyt_wifiOn",
    "icon-hyt_wifiOnFilled",
    "icon-hyt_arrowLeft",
    "icon-hyt_arrowUp",
    "icon-hyt_arrowDown",
    "icon-hyt_arrowRight",
    "icon-hyt_fieldsPlus-copia",
    "icon-hyt_homeNew",
    "icon-hyt_join_Broken",
    "icon-hyt_key",
    "icon-hyt_pencil",
    "icon-hyt_pencil_Negative",
    "icon-hyt_cancelX",
    "icon-hyt_projects_Negative",
    "icon-hyt_projectsR_Negative",
    "icon-hyt_Security",
    "icon-hyt_Trusted",
    "icon-hyt_warnC_Negative",
    "icon-hyt_warnT_Negative",
    "icon-hyt_connectorPlugged",
    "icon-hyt_connector",
    "icon-hyt_connectorNoFramePlugged",
    "icon-hyt_connectorNoFrame",
    "icon-hyt_Undo2",
    "icon-hyt_Undo",
    "icon-hyt_Undo-copia",
    "icon-hyt_power1",
    "icon-hyt_streamData_Wifi",
    "icon-hyt_streamData_Play",
    "icon-hyt_streamData_Power",
    "icon-hyt_streamData_Mobile",
    "icon-hyt_streamData_Save",
    "icon-hyt_streamData_Lamp",
    "icon-hyt_streamCloud_Wifi",
    "icon-hyt_streamCloud_Save",
    "icon-hyt_streamCloud_Power",
    "icon-hyt_streamCloud_Play",
    "icon-hyt_streamCloud_Mobile",
    "icon-hyt_streamCloud_Lamp",
    "icon-hyt_app",
    "icon-hyt_appB",
    "icon-hyt_area12",
    "icon-hyt_area16",
    "icon-hyt_areaB12",
    "icon-hyt_areaB16",
    "icon-hyt_db",
    "icon-hyt_algorithm",
    "icon-hyt_deviceOUT",
    "icon-hyt_deviceIN",
    "icon-hyt_file",
    "icon-hyt_upload",
    "icon-hyt_filter",
    "icon-hyt_filterSetting",
    "icon-hyt_filterRound",
    "icon-hyt_power",
    "icon-hyt_run",
    "icon-hyt_maximize",
    "icon-hyt_maximizeRounded",
    "icon-hyt_maximizeArrow",
    "icon-hyt_minimize",
    "icon-hyt_minimizeRounded",
    "icon-hyt_minimizeArrow",
    "icon-hyt_machine04",
    "icon-hyt_machine05",
    "icon-hyt_source02",
  ];
  faIconList = [
    "fa fa-glass",
    "fa fa-music",
    "fa fa-search",
    "fa fa-envelope-o",
    "fa fa-heart",
    "fa fa-star",
    "fa fa-star-o",
    "fa fa-user",
    "fa fa-film",
    "fa fa-th-large",
    "fa fa-th",
    "fa fa-th-list",
    "fa fa-check",
    "fa fa-times",
    "fa fa-search-plus",
    "fa fa-search-minus",
    "fa fa-power-off",
    "fa fa-signal",
    "fa fa-gear",
    "fa fa-cog",
    "fa fa-trash-o",
    "fa fa-home",
    "fa fa-file-o",
    "fa fa-clock-o",
    "fa fa-road",
    "fa fa-download",
    "fa fa-arrow-circle-o-down",
    "fa fa-arrow-circle-o-up",
    "fa fa-inbox",
    "fa fa-play-circle-o",
    "fa fa-rotate-right",
    "fa fa-repeat",
    "fa fa-refresh",
    "fa fa-list-alt",
    "fa fa-lock",
    "fa fa-flag",
    "fa fa-headphones",
    "fa fa-volume-off",
    "fa fa-volume-down",
    "fa fa-volume-up",
    "fa fa-qrcode",
    "fa fa-barcode",
    "fa fa-tag",
    "fa fa-tags",
    "fa fa-book",
    "fa fa-bookmark",
    "fa fa-print",
    "fa fa-camera",
    "fa fa-font",
    "fa fa-bold",
    "fa fa-italic",
    "fa fa-text-height",
    "fa fa-text-width",
    "fa fa-align-left",
    "fa fa-align-center",
    "fa fa-align-right",
    "fa fa-align-justify",
    "fa fa-list",
    "fa fa-dedent",
    "fa fa-outdent",
    "fa fa-indent",
    "fa fa-video-camera",
    "fa fa-picture-o",
    "fa fa-pencil",
    "fa fa-map-marker",
    "fa fa-adjust",
    "fa fa-tint",
    "fa fa-edit",
    "fa fa-pencil-square-o",
    "fa fa-share-square-o",
    "fa fa-check-square-o",
    "fa fa-arrows",
    "fa fa-step-backward",
    "fa fa-fast-backward",
    "fa fa-backward",
    "fa fa-play",
    "fa fa-pause",
    "fa fa-stop",
    "fa fa-forward",
    "fa fa-fast-forward",
    "fa fa-step-forward",
    "fa fa-eject",
    "fa fa-chevron-left",
    "fa fa-chevron-right",
    "fa fa-plus-circle",
    "fa fa-minus-circle",
    "fa fa-times-circle",
    "fa fa-check-circle",
    "fa fa-question-circle",
    "fa fa-info-circle",
    "fa fa-crosshairs",
    "fa fa-times-circle-o",
    "fa fa-check-circle-o",
    "fa fa-ban",
    "fa fa-arrow-left",
    "fa fa-arrow-right",
    "fa fa-arrow-up",
    "fa fa-arrow-down",
    "fa fa-mail-forward",
    "fa fa-share",
    "fa fa-expand",
    "fa fa-compress",
    "fa fa-plus",
    "fa fa-minus",
    "fa fa-asterisk",
    "fa fa-exclamation-circle",
    "fa fa-gift",
    "fa fa-leaf",
    "fa fa-fire",
    "fa fa-eye",
    "fa fa-eye-slash",
    "fa fa-warning",
    "fa fa-exclamation-triangle",
    "fa fa-plane",
    "fa fa-calendar",
    "fa fa-random",
    "fa fa-comment",
    "fa fa-magnet",
    "fa fa-chevron-up",
    "fa fa-chevron-down",
    "fa fa-retweet",
    "fa fa-shopping-cart",
    "fa fa-folder",
    "fa fa-folder-open",
    "fa fa-arrows-v",
    "fa fa-arrows-h",
    "fa fa-bar-chart-o",
    "fa fa-twitter-square",
    "fa fa-facebook-square",
    "fa fa-camera-retro",
    "fa fa-key",
    "fa fa-gears",
    "fa fa-cogs",
    "fa fa-comments",
    "fa fa-thumbs-o-up",
    "fa fa-thumbs-o-down",
    "fa fa-star-half",
    "fa fa-heart-o",
    "fa fa-sign-out",
    "fa fa-linkedin-square",
    "fa fa-thumb-tack",
    "fa fa-external-link",
    "fa fa-sign-in",
    "fa fa-trophy",
    "fa fa-github-square",
    "fa fa-upload",
    "fa fa-lemon-o",
    "fa fa-phone",
    "fa fa-square-o",
    "fa fa-bookmark-o",
    "fa fa-phone-square",
    "fa fa-twitter",
    "fa fa-facebook",
    "fa fa-github",
    "fa fa-unlock",
    "fa fa-credit-card",
    "fa fa-rss",
    "fa fa-hdd-o",
    "fa fa-bullhorn",
    "fa fa-bell",
    "fa fa-certificate",
    "fa fa-hand-o-right",
    "fa fa-hand-o-left",
    "fa fa-hand-o-up",
    "fa fa-hand-o-down",
    "fa fa-arrow-circle-left",
    "fa fa-arrow-circle-right",
    "fa fa-arrow-circle-up",
    "fa fa-arrow-circle-down",
    "fa fa-globe",
    "fa fa-wrench",
    "fa fa-tasks",
    "fa fa-filter",
    "fa fa-briefcase",
    "fa fa-arrows-alt",
    "fa fa-group",
    "fa fa-users",
    "fa fa-chain",
    "fa fa-link",
    "fa fa-cloud",
    "fa fa-flask",
    "fa fa-cut",
    "fa fa-scissors",
    "fa fa-copy",
    "fa fa-files-o",
    "fa fa-paperclip",
    "fa fa-save",
    "fa fa-floppy-o",
    "fa fa-square",
    "fa fa-bars",
    "fa fa-list-ul",
    "fa fa-list-ol",
    "fa fa-strikethrough",
    "fa fa-underline",
    "fa fa-table",
    "fa fa-magic",
    "fa fa-truck",
    "fa fa-pinterest",
    "fa fa-pinterest-square",
    "fa fa-google-plus-square",
    "fa fa-google-plus",
    "fa fa-money",
    "fa fa-caret-down",
    "fa fa-caret-up",
    "fa fa-caret-left",
    "fa fa-caret-right",
    "fa fa-columns",
    "fa fa-unsorted",
    "fa fa-sort",
    "fa fa-sort-down",
    "fa fa-sort-asc",
    "fa fa-sort-up",
    "fa fa-sort-desc",
    "fa fa-envelope",
    "fa fa-linkedin",
    "fa fa-rotate-left",
    "fa fa-undo",
    "fa fa-legal",
    "fa fa-gavel",
    "fa fa-dashboard",
    "fa fa-tachometer",
    "fa fa-comment-o",
    "fa fa-comments-o",
    "fa fa-flash",
    "fa fa-bolt",
    "fa fa-sitemap",
    "fa fa-umbrella",
    "fa fa-paste",
    "fa fa-clipboard",
    "fa fa-lightbulb-o",
    "fa fa-exchange",
    "fa fa-cloud-download",
    "fa fa-cloud-upload",
    "fa fa-user-md",
    "fa fa-stethoscope",
    "fa fa-suitcase",
    "fa fa-bell-o",
    "fa fa-coffee",
    "fa fa-cutlery",
    "fa fa-file-text-o",
    "fa fa-building-o",
    "fa fa-hospital-o",
    "fa fa-ambulance",
    "fa fa-medkit",
    "fa fa-fighter-jet",
    "fa fa-beer",
    "fa fa-h-square",
    "fa fa-plus-square",
    "fa fa-angle-double-left",
    "fa fa-angle-double-right",
    "fa fa-angle-double-up",
    "fa fa-angle-double-down",
    "fa fa-angle-left",
    "fa fa-angle-right",
    "fa fa-angle-up",
    "fa fa-angle-down",
    "fa fa-desktop",
    "fa fa-laptop",
    "fa fa-tablet",
    "fa fa-mobile-phone",
    "fa fa-mobile",
    "fa fa-circle-o",
    "fa fa-quote-left",
    "fa fa-quote-right",
    "fa fa-spinner",
    "fa fa-circle",
    "fa fa-mail-reply",
    "fa fa-reply",
    "fa fa-github-alt",
    "fa fa-folder-o",
    "fa fa-folder-open-o",
    "fa fa-smile-o",
    "fa fa-frown-o",
    "fa fa-meh-o",
    "fa fa-gamepad",
    "fa fa-keyboard-o",
    "fa fa-flag-o",
    "fa fa-flag-checkered",
    "fa fa-terminal",
    "fa fa-code",
    "fa fa-reply-all",
    "fa fa-mail-reply-all",
    "fa fa-star-half-empty",
    "fa fa-star-half-full",
    "fa fa-star-half-o",
    "fa fa-location-arrow",
    "fa fa-crop",
    "fa fa-code-fork",
    "fa fa-unlink",
    "fa fa-chain-broken",
    "fa fa-question",
    "fa fa-info",
    "fa fa-exclamation",
    "fa fa-superscript",
    "fa fa-subscript",
    "fa fa-eraser",
    "fa fa-puzzle-piece",
    "fa fa-microphone",
    "fa fa-microphone-slash",
    "fa fa-shield",
    "fa fa-calendar-o",
    "fa fa-fire-extinguisher",
    "fa fa-rocket",
    "fa fa-maxcdn",
    "fa fa-chevron-circle-left",
    "fa fa-chevron-circle-right",
    "fa fa-chevron-circle-up",
    "fa fa-chevron-circle-down",
    "fa fa-html5",
    "fa fa-css3",
    "fa fa-anchor",
    "fa fa-unlock-alt",
    "fa fa-bullseye",
    "fa fa-ellipsis-h",
    "fa fa-ellipsis-v",
    "fa fa-rss-square",
    "fa fa-play-circle",
    "fa fa-ticket",
    "fa fa-minus-square",
    "fa fa-minus-square-o",
    "fa fa-level-up",
    "fa fa-level-down",
    "fa fa-check-square",
    "fa fa-pencil-square",
    "fa fa-external-link-square",
    "fa fa-share-square",
    "fa fa-compass",
    "fa fa-toggle-down",
    "fa fa-caret-square-o-down",
    "fa fa-toggle-up",
    "fa fa-caret-square-o-up",
    "fa fa-toggle-right",
    "fa fa-caret-square-o-right",
    "fa fa-euro",
    "fa fa-eur",
    "fa fa-gbp",
    "fa fa-dollar",
    "fa fa-usd",
    "fa fa-rupee",
    "fa fa-inr",
    "fa fa-cny",
    "fa fa-rmb",
    "fa fa-yen",
    "fa fa-jpy",
    "fa fa-ruble",
    "fa fa-rouble",
    "fa fa-rub",
    "fa fa-won",
    "fa fa-krw",
    "fa fa-bitcoin",
    "fa fa-btc",
    "fa fa-file",
    "fa fa-file-text",
    "fa fa-sort-alpha-asc",
    "fa fa-sort-alpha-desc",
    "fa fa-sort-amount-asc",
    "fa fa-sort-amount-desc",
    "fa fa-sort-numeric-asc",
    "fa fa-sort-numeric-desc",
    "fa fa-thumbs-up",
    "fa fa-thumbs-down",
    "fa fa-youtube-square",
    "fa fa-youtube",
    "fa fa-xing",
    "fa fa-xing-square",
    "fa fa-youtube-play",
    "fa fa-dropbox",
    "fa fa-stack-overflow",
    "fa fa-instagram",
    "fa fa-flickr",
    "fa fa-adn",
    "fa fa-bitbucket",
    "fa fa-bitbucket-square",
    "fa fa-tumblr",
    "fa fa-tumblr-square",
    "fa fa-long-arrow-down",
    "fa fa-long-arrow-up",
    "fa fa-long-arrow-left",
    "fa fa-long-arrow-right",
    "fa fa-apple",
    "fa fa-windows",
    "fa fa-android",
    "fa fa-linux",
    "fa fa-dribbble",
    "fa fa-skype",
    "fa fa-foursquare",
    "fa fa-trello",
    "fa fa-female",
    "fa fa-male",
    "fa fa-gittip",
    "fa fa-sun-o",
    "fa fa-moon-o",
    "fa fa-archive",
    "fa fa-bug",
    "fa fa-vk",
    "fa fa-weibo",
    "fa fa-renren",
    "fa fa-pagelines",
    "fa fa-stack-exchange",
    "fa fa-arrow-circle-o-right",
    "fa fa-arrow-circle-o-left",
    "fa fa-toggle-left",
    "fa fa-caret-square-o-left",
    "fa fa-dot-circle-o",
    "fa fa-wheelchair",
    "fa fa-vimeo-square",
    "fa fa-turkish-lira",
    "fa fa-try",
    "fa fa-plus-square-o",
  ];

  constructor(
    private dialogRef: DialogRef<any>,
    @Inject(DIALOG_DATA) public data: { selectedIcon: string; },
  ) { }

  ngOnInit(): void {
    this.allIcons = this.hytIconList.concat(this.faIconList);
    this.filterIconList();
  }

  filterIconList() {
    this.filteredIcons = this.allIcons.filter(icon => icon.includes(this.filterValue));
    this.filteredIcons.unshift('');
  }

  onIconSelected(icon) {
    this.close(icon);
  }

  close(result) {
    this.dialogRef.close(result);
  }
}
