import { Component, Inject, OnInit } from '@angular/core';
import { DialogRef } from '../../hyt-dialog/dialog-ref';
import { DIALOG_DATA } from '../../hyt-dialog/dialog-tokens';

@Component({
  selector: 'hyt-icon-picker-list',
  templateUrl: './hyt-icon-picker-list.component.html',
  styleUrls: ['./hyt-icon-picker-list.component.scss']
})
export class HytIconPickerListComponent implements OnInit {

  allIcons: string[] = [];
  filteredIcons: string[] = [];

  selectedIcon: string = '';

  filterValue = '';

  hytIconList = [
    "hyt-icon icon-hyt_action",
    "hyt-icon icon-hyt_asterisk",
    "hyt-icon icon-hyt_cancel",
    "hyt-icon icon-hyt_cancelC",
    "hyt-icon icon-hyt_caretDown",
    "hyt-icon icon-hyt_caretUp",
    "hyt-icon icon-hyt_categories",
    "hyt-icon icon-hyt_category",
    "hyt-icon icon-hyt_charCake",
    "hyt-icon icon-hyt_chartBar",
    "hyt-icon icon-hyt_chartGauge",
    "hyt-icon icon-hyt_chartLine",
    "hyt-icon icon-hyt_chartRadar",
    "hyt-icon icon-hyt_chip",
    "hyt-icon icon-hyt_clock",
    "hyt-icon icon-hyt_coins",
    "hyt-icon icon-hyt_dash",
    "hyt-icon icon-hyt_dashPlus",
    "hyt-icon icon-hyt_device",
    "hyt-icon icon-hyt_devicePlus",
    "hyt-icon icon-hyt_download",
    "hyt-icon icon-hyt_duplicate",
    "hyt-icon icon-hyt_enrichments",
    "hyt-icon icon-hyt_enrichmentsPlus",
    "hyt-icon icon-hyt_event",
    "hyt-icon icon-hyt_eventPlus",
    "hyt-icon icon-hyt_exL",
    "hyt-icon icon-hyt_exM",
    "hyt-icon icon-hyt_exS",
    "hyt-icon icon-hyt_eyeClose",
    "hyt-icon icon-hyt_eyeOpen",
    "hyt-icon icon-hyt_fields",
    "hyt-icon icon-hyt_fieldsPlus",
    "hyt-icon icon-hyt_hamClose",
    "hyt-icon icon-hyt_hamOpen",
    "hyt-icon icon-hyt_helpM",
    "hyt-icon icon-hyt_helpS",
    "hyt-icon icon-hyt_home",
    "hyt-icon icon-hyt_info",
    "hyt-icon icon-hyt_join",
    "hyt-icon icon-hyt_layout",
    "hyt-icon icon-hyt_layoutPlus",
    "hyt-icon icon-hyt_less",
    "hyt-icon icon-hyt_lessC",
    "hyt-icon icon-hyt_lessX",
    "hyt-icon icon-hyt_lock",
    "hyt-icon icon-hyt_mail",
    "hyt-icon icon-hyt_map",
    "hyt-icon icon-hyt_notification",
    "hyt-icon icon-hyt_off",
    "hyt-icon icon-hyt_packets",
    "hyt-icon icon-hyt_packetsPlus",
    "hyt-icon icon-hyt_pause",
    "hyt-icon icon-hyt_play",
    "hyt-icon icon-hyt_plus",
    "hyt-icon icon-hyt_plusC",
    "hyt-icon icon-hyt_plusX",
    "hyt-icon icon-hyt_projectRSolo",
    "hyt-icon icon-hyt_projects",
    "hyt-icon icon-hyt_projectSolo",
    "hyt-icon icon-hyt_projectsPlus",
    "hyt-icon icon-hyt_projectsR",
    "hyt-icon icon-hyt_projectsRPlus",
    "hyt-icon icon-hyt_reload",
    "hyt-icon icon-hyt_save",
    "hyt-icon icon-hyt_search",
    "hyt-icon icon-hyt_setting",
    "hyt-icon icon-hyt_sortAlfa",
    "hyt-icon icon-hyt_sortDown",
    "hyt-icon icon-hyt_sortStar",
    "hyt-icon icon-hyt_sortUp",
    "hyt-icon icon-hyt_star",
    "hyt-icon icon-hyt_statistics",
    "hyt-icon icon-hyt_statisticsPlus",
    "hyt-icon icon-hyt_stop",
    "hyt-icon icon-hyt_switch",
    "hyt-icon icon-hyt_tableBig",
    "hyt-icon icon-hyt_tabLight",
    "hyt-icon icon-hyt_tag",
    "hyt-icon icon-hyt_tags",
    "hyt-icon icon-hyt_trash",
    "hyt-icon icon-hyt_user",
    "hyt-icon icon-hyt_userCircle",
    "hyt-icon icon-hyt_userEx",
    "hyt-icon icon-hyt_valid",
    "hyt-icon icon-hyt_warnC",
    "hyt-icon icon-hyt_warnT",
    "hyt-icon icon-hyt_widget",
    "hyt-icon icon-hyt_widgetPlus",
    "hyt-icon icon-hyt_wifiOff",
    "hyt-icon icon-hyt_wifiOffFilled",
    "hyt-icon icon-hyt_wifiOn",
    "hyt-icon icon-hyt_wifiOnFilled",
    "hyt-icon icon-hyt_arrowLeft",
    "hyt-icon icon-hyt_arrowUp",
    "hyt-icon icon-hyt_arrowDown",
    "hyt-icon icon-hyt_arrowRight",
    "hyt-icon icon-hyt_fieldsPlus-copia",
    "hyt-icon icon-hyt_homeNew",
    "hyt-icon icon-hyt_join_Broken",
    "hyt-icon icon-hyt_key",
    "hyt-icon icon-hyt_pencil",
    "hyt-icon icon-hyt_pencil_Negative",
    "hyt-icon icon-hyt_cancelX",
    "hyt-icon icon-hyt_projects_Negative",
    "hyt-icon icon-hyt_projectsR_Negative",
    "hyt-icon icon-hyt_Security",
    "hyt-icon icon-hyt_Trusted",
    "hyt-icon icon-hyt_warnC_Negative",
    "hyt-icon icon-hyt_warnT_Negative",
    "hyt-icon icon-hyt_connectorPlugged",
    "hyt-icon icon-hyt_connector",
    "hyt-icon icon-hyt_connectorNoFramePlugged",
    "hyt-icon icon-hyt_connectorNoFrame",
    "hyt-icon icon-hyt_Undo2",
    "hyt-icon icon-hyt_Undo",
    "hyt-icon icon-hyt_Undo-copia",
    "hyt-icon icon-hyt_power1",
    "hyt-icon icon-hyt_streamData_Wifi",
    "hyt-icon icon-hyt_streamData_Play",
    "hyt-icon icon-hyt_streamData_Power",
    "hyt-icon icon-hyt_streamData_Mobile",
    "hyt-icon icon-hyt_streamData_Save",
    "hyt-icon icon-hyt_streamData_Lamp",
    "hyt-icon icon-hyt_streamCloud_Wifi",
    "hyt-icon icon-hyt_streamCloud_Save",
    "hyt-icon icon-hyt_streamCloud_Power",
    "hyt-icon icon-hyt_streamCloud_Play",
    "hyt-icon icon-hyt_streamCloud_Mobile",
    "hyt-icon icon-hyt_streamCloud_Lamp",
    "hyt-icon icon-hyt_app",
    "hyt-icon icon-hyt_appB",
    "hyt-icon icon-hyt_area12",
    "hyt-icon icon-hyt_area16",
    "hyt-icon icon-hyt_areaB12",
    "hyt-icon icon-hyt_areaB16",
    "hyt-icon icon-hyt_db",
    "hyt-icon icon-hyt_algorithm",
    "hyt-icon icon-hyt_deviceOUT",
    "hyt-icon icon-hyt_deviceIN",
    "hyt-icon icon-hyt_file",
    "hyt-icon icon-hyt_upload",
    "hyt-icon icon-hyt_filter",
    "hyt-icon icon-hyt_filterSetting",
    "hyt-icon icon-hyt_filterRound",
    "hyt-icon icon-hyt_power",
    "hyt-icon icon-hyt_run",
    "hyt-icon icon-hyt_maximize",
    "hyt-icon icon-hyt_maximizeRounded",
    "hyt-icon icon-hyt_maximizeArrow",
    "hyt-icon icon-hyt_minimize",
    "hyt-icon icon-hyt_minimizeRounded",
    "hyt-icon icon-hyt_minimizeArrow",
    "hyt-icon icon-hyt_machine04",
    "hyt-icon icon-hyt_machine05",
    "hyt-icon icon-hyt_source02",
  ];
  faIconList = [
    "fa fa-glass",
    "fa fa-music",
    "fa fa-search",
    "fa fa-envelope-o",
    "fa fa-heart",
    "fa fa-star",
    "fa fa-star-o",
    "fa fa-user",
    "fa fa-film",
    "fa fa-th-large",
    "fa fa-th",
    "fa fa-th-list",
    "fa fa-check",
    "fa fa-times",
    "fa fa-search-plus",
    "fa fa-search-minus",
    "fa fa-power-off",
    "fa fa-signal",
    "fa fa-gear",
    "fa fa-cog",
    "fa fa-trash-o",
    "fa fa-home",
    "fa fa-file-o",
    "fa fa-clock-o",
    "fa fa-road",
    "fa fa-download",
    "fa fa-arrow-circle-o-down",
    "fa fa-arrow-circle-o-up",
    "fa fa-inbox",
    "fa fa-play-circle-o",
    "fa fa-rotate-right",
    "fa fa-repeat",
    "fa fa-refresh",
    "fa fa-list-alt",
    "fa fa-lock",
    "fa fa-flag",
    "fa fa-headphones",
    "fa fa-volume-off",
    "fa fa-volume-down",
    "fa fa-volume-up",
    "fa fa-qrcode",
    "fa fa-barcode",
    "fa fa-tag",
    "fa fa-tags",
    "fa fa-book",
    "fa fa-bookmark",
    "fa fa-print",
    "fa fa-camera",
    "fa fa-font",
    "fa fa-bold",
    "fa fa-italic",
    "fa fa-text-height",
    "fa fa-text-width",
    "fa fa-align-left",
    "fa fa-align-center",
    "fa fa-align-right",
    "fa fa-align-justify",
    "fa fa-list",
    "fa fa-dedent",
    "fa fa-outdent",
    "fa fa-indent",
    "fa fa-video-camera",
    "fa fa-picture-o",
    "fa fa-pencil",
    "fa fa-map-marker",
    "fa fa-adjust",
    "fa fa-tint",
    "fa fa-edit",
    "fa fa-pencil-square-o",
    "fa fa-share-square-o",
    "fa fa-check-square-o",
    "fa fa-arrows",
    "fa fa-step-backward",
    "fa fa-fast-backward",
    "fa fa-backward",
    "fa fa-play",
    "fa fa-pause",
    "fa fa-stop",
    "fa fa-forward",
    "fa fa-fast-forward",
    "fa fa-step-forward",
    "fa fa-eject",
    "fa fa-chevron-left",
    "fa fa-chevron-right",
    "fa fa-plus-circle",
    "fa fa-minus-circle",
    "fa fa-times-circle",
    "fa fa-check-circle",
    "fa fa-question-circle",
    "fa fa-info-circle",
    "fa fa-crosshairs",
    "fa fa-times-circle-o",
    "fa fa-check-circle-o",
    "fa fa-ban",
    "fa fa-arrow-left",
    "fa fa-arrow-right",
    "fa fa-arrow-up",
    "fa fa-arrow-down",
    "fa fa-mail-forward",
    "fa fa-share",
    "fa fa-expand",
    "fa fa-compress",
    "fa fa-plus",
    "fa fa-minus",
    "fa fa-asterisk",
    "fa fa-exclamation-circle",
    "fa fa-gift",
    "fa fa-leaf",
    "fa fa-fire",
    "fa fa-eye",
    "fa fa-eye-slash",
    "fa fa-warning",
    "fa fa-exclamation-triangle",
    "fa fa-plane",
    "fa fa-calendar",
    "fa fa-random",
    "fa fa-comment",
    "fa fa-magnet",
    "fa fa-chevron-up",
    "fa fa-chevron-down",
    "fa fa-retweet",
    "fa fa-shopping-cart",
    "fa fa-folder",
    "fa fa-folder-open",
    "fa fa-arrows-v",
    "fa fa-arrows-h",
    "fa fa-bar-chart-o",
    "fa fa-twitter-square",
    "fa fa-facebook-square",
    "fa fa-camera-retro",
    "fa fa-key",
    "fa fa-gears",
    "fa fa-cogs",
    "fa fa-comments",
    "fa fa-thumbs-o-up",
    "fa fa-thumbs-o-down",
    "fa fa-star-half",
    "fa fa-heart-o",
    "fa fa-sign-out",
    "fa fa-linkedin-square",
    "fa fa-thumb-tack",
    "fa fa-external-link",
    "fa fa-sign-in",
    "fa fa-trophy",
    "fa fa-github-square",
    "fa fa-upload",
    "fa fa-lemon-o",
    "fa fa-phone",
    "fa fa-square-o",
    "fa fa-bookmark-o",
    "fa fa-phone-square",
    "fa fa-twitter",
    "fa fa-facebook",
    "fa fa-github",
    "fa fa-unlock",
    "fa fa-credit-card",
    "fa fa-rss",
    "fa fa-hdd-o",
    "fa fa-bullhorn",
    "fa fa-bell",
    "fa fa-certificate",
    "fa fa-hand-o-right",
    "fa fa-hand-o-left",
    "fa fa-hand-o-up",
    "fa fa-hand-o-down",
    "fa fa-arrow-circle-left",
    "fa fa-arrow-circle-right",
    "fa fa-arrow-circle-up",
    "fa fa-arrow-circle-down",
    "fa fa-globe",
    "fa fa-wrench",
    "fa fa-tasks",
    "fa fa-filter",
    "fa fa-briefcase",
    "fa fa-arrows-alt",
    "fa fa-group",
    "fa fa-users",
    "fa fa-chain",
    "fa fa-link",
    "fa fa-cloud",
    "fa fa-flask",
    "fa fa-cut",
    "fa fa-scissors",
    "fa fa-copy",
    "fa fa-files-o",
    "fa fa-paperclip",
    "fa fa-save",
    "fa fa-floppy-o",
    "fa fa-square",
    "fa fa-bars",
    "fa fa-list-ul",
    "fa fa-list-ol",
    "fa fa-strikethrough",
    "fa fa-underline",
    "fa fa-table",
    "fa fa-magic",
    "fa fa-truck",
    "fa fa-pinterest",
    "fa fa-pinterest-square",
    "fa fa-google-plus-square",
    "fa fa-google-plus",
    "fa fa-money",
    "fa fa-caret-down",
    "fa fa-caret-up",
    "fa fa-caret-left",
    "fa fa-caret-right",
    "fa fa-columns",
    "fa fa-unsorted",
    "fa fa-sort",
    "fa fa-sort-down",
    "fa fa-sort-asc",
    "fa fa-sort-up",
    "fa fa-sort-desc",
    "fa fa-envelope",
    "fa fa-linkedin",
    "fa fa-rotate-left",
    "fa fa-undo",
    "fa fa-legal",
    "fa fa-gavel",
    "fa fa-dashboard",
    "fa fa-tachometer",
    "fa fa-comment-o",
    "fa fa-comments-o",
    "fa fa-flash",
    "fa fa-bolt",
    "fa fa-sitemap",
    "fa fa-umbrella",
    "fa fa-paste",
    "fa fa-clipboard",
    "fa fa-lightbulb-o",
    "fa fa-exchange",
    "fa fa-cloud-download",
    "fa fa-cloud-upload",
    "fa fa-user-md",
    "fa fa-stethoscope",
    "fa fa-suitcase",
    "fa fa-bell-o",
    "fa fa-coffee",
    "fa fa-cutlery",
    "fa fa-file-text-o",
    "fa fa-building-o",
    "fa fa-hospital-o",
    "fa fa-ambulance",
    "fa fa-medkit",
    "fa fa-fighter-jet",
    "fa fa-beer",
    "fa fa-h-square",
    "fa fa-plus-square",
    "fa fa-angle-double-left",
    "fa fa-angle-double-right",
    "fa fa-angle-double-up",
    "fa fa-angle-double-down",
    "fa fa-angle-left",
    "fa fa-angle-right",
    "fa fa-angle-up",
    "fa fa-angle-down",
    "fa fa-desktop",
    "fa fa-laptop",
    "fa fa-tablet",
    "fa fa-mobile-phone",
    "fa fa-mobile",
    "fa fa-circle-o",
    "fa fa-quote-left",
    "fa fa-quote-right",
    "fa fa-spinner",
    "fa fa-circle",
    "fa fa-mail-reply",
    "fa fa-reply",
    "fa fa-github-alt",
    "fa fa-folder-o",
    "fa fa-folder-open-o",
    "fa fa-smile-o",
    "fa fa-frown-o",
    "fa fa-meh-o",
    "fa fa-gamepad",
    "fa fa-keyboard-o",
    "fa fa-flag-o",
    "fa fa-flag-checkered",
    "fa fa-terminal",
    "fa fa-code",
    "fa fa-reply-all",
    "fa fa-mail-reply-all",
    "fa fa-star-half-empty",
    "fa fa-star-half-full",
    "fa fa-star-half-o",
    "fa fa-location-arrow",
    "fa fa-crop",
    "fa fa-code-fork",
    "fa fa-unlink",
    "fa fa-chain-broken",
    "fa fa-question",
    "fa fa-info",
    "fa fa-exclamation",
    "fa fa-superscript",
    "fa fa-subscript",
    "fa fa-eraser",
    "fa fa-puzzle-piece",
    "fa fa-microphone",
    "fa fa-microphone-slash",
    "fa fa-shield",
    "fa fa-calendar-o",
    "fa fa-fire-extinguisher",
    "fa fa-rocket",
    "fa fa-maxcdn",
    "fa fa-chevron-circle-left",
    "fa fa-chevron-circle-right",
    "fa fa-chevron-circle-up",
    "fa fa-chevron-circle-down",
    "fa fa-html5",
    "fa fa-css3",
    "fa fa-anchor",
    "fa fa-unlock-alt",
    "fa fa-bullseye",
    "fa fa-ellipsis-h",
    "fa fa-ellipsis-v",
    "fa fa-rss-square",
    "fa fa-play-circle",
    "fa fa-ticket",
    "fa fa-minus-square",
    "fa fa-minus-square-o",
    "fa fa-level-up",
    "fa fa-level-down",
    "fa fa-check-square",
    "fa fa-pencil-square",
    "fa fa-external-link-square",
    "fa fa-share-square",
    "fa fa-compass",
    "fa fa-toggle-down",
    "fa fa-caret-square-o-down",
    "fa fa-toggle-up",
    "fa fa-caret-square-o-up",
    "fa fa-toggle-right",
    "fa fa-caret-square-o-right",
    "fa fa-euro",
    "fa fa-eur",
    "fa fa-gbp",
    "fa fa-dollar",
    "fa fa-usd",
    "fa fa-rupee",
    "fa fa-inr",
    "fa fa-cny",
    "fa fa-rmb",
    "fa fa-yen",
    "fa fa-jpy",
    "fa fa-ruble",
    "fa fa-rouble",
    "fa fa-rub",
    "fa fa-won",
    "fa fa-krw",
    "fa fa-bitcoin",
    "fa fa-btc",
    "fa fa-file",
    "fa fa-file-text",
    "fa fa-sort-alpha-asc",
    "fa fa-sort-alpha-desc",
    "fa fa-sort-amount-asc",
    "fa fa-sort-amount-desc",
    "fa fa-sort-numeric-asc",
    "fa fa-sort-numeric-desc",
    "fa fa-thumbs-up",
    "fa fa-thumbs-down",
    "fa fa-youtube-square",
    "fa fa-youtube",
    "fa fa-xing",
    "fa fa-xing-square",
    "fa fa-youtube-play",
    "fa fa-dropbox",
    "fa fa-stack-overflow",
    "fa fa-instagram",
    "fa fa-flickr",
    "fa fa-adn",
    "fa fa-bitbucket",
    "fa fa-bitbucket-square",
    "fa fa-tumblr",
    "fa fa-tumblr-square",
    "fa fa-long-arrow-down",
    "fa fa-long-arrow-up",
    "fa fa-long-arrow-left",
    "fa fa-long-arrow-right",
    "fa fa-apple",
    "fa fa-windows",
    "fa fa-android",
    "fa fa-linux",
    "fa fa-dribbble",
    "fa fa-skype",
    "fa fa-foursquare",
    "fa fa-trello",
    "fa fa-female",
    "fa fa-male",
    "fa fa-gittip",
    "fa fa-sun-o",
    "fa fa-moon-o",
    "fa fa-archive",
    "fa fa-bug",
    "fa fa-vk",
    "fa fa-weibo",
    "fa fa-renren",
    "fa fa-pagelines",
    "fa fa-stack-exchange",
    "fa fa-arrow-circle-o-right",
    "fa fa-arrow-circle-o-left",
    "fa fa-toggle-left",
    "fa fa-caret-square-o-left",
    "fa fa-dot-circle-o",
    "fa fa-wheelchair",
    "fa fa-vimeo-square",
    "fa fa-turkish-lira",
    "fa fa-try",
    "fa fa-plus-square-o",
  ];
  matIconList = [
    "3d_rotation",
    "ac_unit",
    "access_alarm",
    "access_alarms",
    "access_time",
    "accessibility",
    "accessible",
    "account_balance",
    "account_balance_wallet",
    "account_box",
    "account_circle",
    "account_tree",
    "adb",
    "add",
    "add_a_photo",
    "add_alarm",
    "add_alert",
    "add_box",
    "add_business",
    "add_call",
    "add_chart",
    "add_circle",
    "add_circle_outline",
    "add_comment",
    "add_ic_call",
    "add_link",
    "add_location",
    "add_moderator",
    "add_photo_alternate",
    "add_reaction",
    "add_road",
    "add_shopping_cart",
    "add_task",
    "add_to_drive",
    "add_to_home_screen",
    "add_to_photos",
    "add_to_queue",
    "addchart",
    "adjust",
    "admin_panel_settings",
    "agriculture",
    "air",
    "airline_seat_flat",
    "airline_seat_flat_angled",
    "airline_seat_individual_suite",
    "airline_seat_legroom_extra",
    "airline_seat_legroom_normal",
    "airline_seat_legroom_reduced",
    "airline_seat_recline_extra",
    "airline_seat_recline_normal",
    "airplanemode_active",
    "airplanemode_inactive",
    "airplay",
    "airport_shuttle",
    "alarm",
    "alarm_add",
    "alarm_off",
    "alarm_on",
    "album",
    "align_horizontal_center",
    "align_horizontal_left",
    "align_horizontal_right",
    "align_vertical_bottom",
    "align_vertical_center",
    "align_vertical_top",
    "all_inbox",
    "all_inclusive",
    "all_out",
    "alt_route",
    "alternate_email",
    "analytics",
    "anchor",
    "android",
    "announcement",
    "apartment",
    "api",
    "app_blocking",
    "app_registration",
    "app_settings_alt",
    "approval",
    "apps",
    "architecture",
    "archive",
    "arrow_back",
    "arrow_back_ios",
    "arrow_circle_down",
    "arrow_circle_up",
    "arrow_downward",
    "arrow_drop_down",
    "arrow_drop_down_circle",
    "arrow_drop_up",
    "arrow_forward",
    "arrow_forward_ios",
    "arrow_left",
    "arrow_right",
    "arrow_right_alt",
    "arrow_upward",
    "art_track",
    "article",
    "aspect_ratio",
    "assessment",
    "assignment",
    "assignment_ind",
    "assignment_late",
    "assignment_return",
    "assignment_returned",
    "assignment_turned_in",
    "assistant",
    "assistant_direction",
    "assistant_navigation",
    "assistant_photo",
    "atm",
    "attach_email",
    "attach_file",
    "attach_money",
    "attachment",
    "attractions",
    "attribution",
    "audiotrack",
    "auto_awesome",
    "auto_awesome_mosaic",
    "auto_awesome_motion",
    "auto_delete",
    "auto_fix_high",
    "auto_fix_normal",
    "auto_fix_off",
    "auto_graph",
    "auto_stories",
    "autofps_select",
    "autorenew",
    "av_timer",
    "baby_changing_station",
    "backpack",
    "backspace",
    "backup",
    "backup_table",
    "badge",
    "bakery_dining",
    "balcony",
    "ballot",
    "bar_chart",
    "batch_prediction",
    "bathroom",
    "bathtub",
    "battery_alert",
    "battery_charging_full",
    "battery_full",
    "battery_saver",
    "battery_std",
    "battery_unknown",
    "beach_access",
    "bed",
    "bedroom_baby",
    "bedroom_child",
    "bedroom_parent",
    "bedtime",
    "beenhere",
    "bento",
    "bike_scooter",
    "biotech",
    "blender",
    "block",
    "bloodtype",
    "bluetooth",
    "bluetooth_audio",
    "bluetooth_connected",
    "bluetooth_disabled",
    "bluetooth_searching",
    "blur_circular",
    "blur_linear",
    "blur_off",
    "blur_on",
    "bolt",
    "book",
    "book_online",
    "bookmark",
    "bookmark_add",
    "bookmark_added",
    "bookmark_border",
    "bookmark_remove",
    "bookmarks",
    "border_all",
    "border_bottom",
    "border_clear",
    "border_color",
    "border_horizontal",
    "border_inner",
    "border_left",
    "border_outer",
    "border_right",
    "border_style",
    "border_top",
    "border_vertical",
    "branding_watermark",
    "breakfast_dining",
    "brightness_1",
    "brightness_2",
    "brightness_3",
    "brightness_4",
    "brightness_5",
    "brightness_6",
    "brightness_7",
    "brightness_auto",
    "brightness_high",
    "brightness_low",
    "brightness_medium",
    "broken_image",
    "browser_not_supported",
    "brunch_dining",
    "brush",
    "bubble_chart",
    "bug_report",
    "build",
    "build_circle",
    "burst_mode",
    "bus_alert",
    "business",
    "business_center",
    "cached",
    "cake",
    "calculate",
    "calendar_today",
    "calendar_view_day",
    "calendar_view_month",
    "calendar_view_week",
    "call",
    "call_end",
    "call_made",
    "call_merge",
    "call_missed",
    "call_missed_outgoing",
    "call_received",
    "call_split",
    "call_to_action",
    "camera",
    "camera_alt",
    "camera_enhance",
    "camera_front",
    "camera_indoor",
    "camera_outdoor",
    "camera_rear",
    "camera_roll",
    "cameraswitch",
    "campaign",
    "cancel",
    "cancel_presentation",
    "cancel_schedule_send",
    "car_rental",
    "car_repair",
    "card_giftcard",
    "card_membership",
    "card_travel",
    "carpenter",
    "cases",
    "casino",
    "cast",
    "cast_connected",
    "cast_for_education",
    "category",
    "celebration",
    "cell_wifi",
    "center_focus_strong",
    "center_focus_weak",
    "chair",
    "chair_alt",
    "chalet",
    "change_circle",
    "change_history",
    "charging_station",
    "chat",
    "chat_bubble",
    "chat_bubble_outline",
    "check",
    "check_box",
    "check_box_outline_blank",
    "check_circle",
    "check_circle_outline",
    "checklist",
    "checklist_rtl",
    "checkroom",
    "chevron_left",
    "chevron_right",
    "child_care",
    "child_friendly",
    "chrome_reader_mode",
    "circle",
    "circle_notifications",
    "class_",
    "clean_hands",
    "cleaning_services",
    "clear",
    "clear_all",
    "close",
    "close_fullscreen",
    "closed_caption",
    "closed_caption_disabled",
    "closed_caption_off",
    "cloud",
    "cloud_circle",
    "cloud_done",
    "cloud_download",
    "cloud_off",
    "cloud_queue",
    "cloud_upload",
    "code",
    "collections",
    "collections_bookmark",
    "color_lens",
    "colorize",
    "comment",
    "comment_bank",
    "commute",
    "compare",
    "compare_arrows",
    "compass_calibration",
    "compress",
    "computer",
    "confirmation_num",
    "confirmation_number",
    "connect_without_contact",
    "connected_tv",
    "construction",
    "contact_mail",
    "contact_page",
    "contact_phone",
    "contact_support",
    "contactless",
    "contacts",
    "content_copy",
    "content_cut",
    "content_paste",
    "control_camera",
    "control_point",
    "control_point_duplicate",
    "copy_all",
    "coronavirus",
    "corporate_fare",
    "cottage",
    "countertops",
    "create",
    "create_new_folder",
    "credit_card",
    "credit_card_off",
    "crop",
    "crop_16_9",
    "crop_3_2",
    "crop_5_4",
    "crop_7_5",
    "crop_din",
    "crop_free",
    "crop_landscape",
    "crop_original",
    "crop_portrait",
    "crop_rotate",
    "crop_square",
    "dangerous",
    "dashboard",
    "dashboard_customize",
    "data_usage",
    "date_range",
    "deck",
    "dehaze",
    "delete",
    "    delete_forever",
    "delete_outline",
    "delete_sweep",
    "delivery_dining",
    "departure_board",
    "description",
    "design_services",
    "desktop_access_disabled",
    "desktop_mac",
    "desktop_windows",
    "details",
    "developer_board",
    "developer_mode",
    "device_hub",
    "device_thermostat",
    "device_unknown",
    "devices",
    "devices_other",
    "dialer_sip",
    "dialpad",
    "dining",
    "dinner_dining",
    "directions",
    "directions_bike",
    "directions_boat",
    "directions_bus",
    "directions_car",
    "directions_ferry",
    "directions_off",
    "directions_railway",
    "directions_run",
    "directions_subway",
    "directions_train",
    "directions_transit",
    "directions_walk",
    "dirty_lens",
    "disabled_by_default",
    "disc_full",
    "dnd_forwardslash",
    "dns",
    "do_not_disturb",
    "do_not_disturb_alt",
    "do_not_disturb_off",
    "do_not_disturb_on",
    "do_not_step",
    "do_not_touch",
    "dock",
    "document_scanner",
    "domain",
    "domain_disabled",
    "domain_verification",
    "done",
    "done_all",
    "done_outline",
    "donut_large",
    "donut_small",
    "door_back",
    "door_front",
    "door_sliding",
    "doorbell",
    "double_arrow",
    "downhill_skiing",
    "download",
    "download_done",
    "download_for_offline",
    "downloading",
    "drafts",
    "drag_handle",
    "drag_indicator",
    "drive_eta",
    "drive_file_move",
    "drive_file_move_outline",
    "drive_file_rename_outline",
    "drive_folder_upload",
    "dry",
    "dry_cleaning",
    "duo",
    "dvr",
    "dynamic_feed",
    "dynamic_form",
    "east",
    "eco",
    "edit",
    "edit_attributes",
    "edit_calendar",
    "edit_location",
    "edit_off",
    "edit_road",
    "eject",
    "elderly",
    "electric_bike",
    "electric_car",
    "electric_moped",
    "electric_rickshaw",
    "electric_scooter",
    "electrical_services",
    "elevator",
    "email",
    "emoji_emotions",
    "emoji_events",
    "emoji_flags",
    "emoji_food_beverage",
    "emoji_nature",
    "emoji_objects",
    "emoji_people",
    "emoji_symbols",
    "emoji_transportation",
    "engineering",
    "enhanced_encryption",
    "equalizer",
    "error",
    "error_outline",
    "escalator",
    "escalator_warning",
    "euro",
    "euro_symbol",
    "ev_station",
    "event",
    "event_available",
    "event_busy",
    "event_note",
    "event_seat",
    "exit_to_app",
    "expand",
    "expand_less",
    "expand_more",
    "explicit",
    "explore",
    "explore_off",
    "exposure",
    "exposure_minus_1",
    "exposure_minus_2",
    "exposure_neg_1",
    "exposure_neg_2",
    "exposure_plus_1",
    "exposure_plus_2",
    "exposure_zero",
    "extension",
    "extension_off",
    "face",
    "face_retouching_natural",
    "facebook",
    "fact_check",
    "family_restroom",
    "fast_forward",
    "fast_rewind",
    "fastfood",
    "favorite",
    "favorite_border",
    "favorite_outline",
    "featured_play_list",
    "featured_video",
    "feedback",
    "fence",
    "festival",
    "fiber_dvr",
    "fiber_manual_record",
    "fiber_new",
    "fiber_pin",
    "fiber_smart_record",
    "file_copy",
    "file_download",
    "file_download_done",
    "file_download_off",
    "file_present",
    "file_upload",
    "filter",
    "filter_alt",
    "filter_b_and_w",
    "filter_center_focus",
    "filter_drama",
    "filter_frames",
    "filter_hdr",
    "filter_list",
    "filter_none",
    "filter_tilt_shift",
    "filter_vintage",
    "find_in_page",
    "find_replace",
    "fingerprint",
    "fire_extinguisher",
    "fire_hydrant",
    "fireplace",
    "first_page",
    "fit_screen",
    "fitness_center",
    "flag",
    "flaky",
    "flare",
    "flash_auto",
    "flash_off",
    "flash_on",
    "flight",
    "flight_land",
    "flight_takeoff",
    "flip",
    "flip_camera_android",
    "flip_camera_ios",
    "flip_to_back",
    "flip_to_front",
    "folder",
    "folder_open",
    "folder_shared",
    "folder_special",
    "follow_the_signs",
    "font_download",
    "food_bank",
    "format_align_center",
    "format_align_justify",
    "format_align_left",
    "format_align_right",
    "format_bold",
    "format_clear",
    "format_color_fill",
    "format_color_reset",
    "format_color_text",
    "format_indent_decrease",
    "format_indent_increase",
    "format_italic",
    "format_line_spacing",
    "format_list_bulleted",
    "format_list_numbered",
    "format_list_numbered_rtl",
    "format_paint",
    "format_quote",
    "format_shapes",
    "format_size",
    "format_strikethrough",
    "format_textdirection_l_to_r",
    "format_textdirection_r_to_l",
    "format_underline",
    "format_underlined",
    "forum",
    "forward",
    "forward_10",
    "forward_30",
    "forward_5",
    "forward_to_inbox",
    "foundation",
    "free_breakfast",
    "free_cancellation",
    "front_hand",
    "fullscreen",
    "fullscreen_exit",
    "functions",
    "g_translate",
    "gamepad",
    "games",
    "garage",
    "gavel",
    "generating_tokens",
    "gesture",
    "get_app",
    "gif",
    "gite",
    "golf_course",
    "gpp_bad",
    "gpp_good",
    "gpp_maybe",
    "gps_fixed",
    "gps_not_fixed",
    "gps_off",
    "grade",
    "gradient",
    "grading",
    "grading_outlined",
    "grading_rounded",
    "grading_sharp",
    "grain",
    "graphic_eq",
    "grass",
    "grid_3x3",
    "grid_4x4",
    "grid_goldenratio",
    "grid_off",
    "grid_on",
    "grid_view",
    "group",
    "group_add",
    "group_off",
    "group_work",
    "groups",
    "hail",
    "handyman",
    "hardware",
    "hd",
    "hdr_auto",
    "hdr_auto_select",
    "hdr_enhanced_select",
    "hdr_off",
    "hdr_off_select",
    "hdr_on",
    "hdr_on_select",
    "hdr_plus",
    "hdr_strong",
    "hdr_weak",
    "headphones",
    "headphones_battery",
    "headset",
    "headset_mic",
    "headset_off",
    "healing",
    "hearing",
    "hearing_disabled",
    "height",
    "help",
    "help_center",
    "help_outline",
    "hevc",
    "hide_image",
    "hide_source",
    "high_quality",
    "highlight",
    "highlight_alt",
    "highlight_off",
    "highlight_remove",
    "history",
    "history_edu",
    "history_toggle_off",
    "holiday_village",
    "home",
    "home_filled",
    "home_repair_service",
    "home_work",
    "horizontal_distribute",
    "horizontal_rule",
    "horizontal_split",
    "hot_tub",
    "hotel",
    "hotel_class",
    "hourglass_bottom",
    "hourglass_disabled",
    "hourglass_empty",
    "hourglass_full",
    "hourglass_top",
    "house",
    "house_siding",
    "how_to_reg",
    "how_to_vote",
    "http",
    "https",
    "icecream",
    "image",
    "image_aspect_ratio",
    "image_not_supported",
    "image_search",
    "imagesearch_roller",
    "import_contacts",
    "import_download",
    "import_export",
    "important_devices",
    "inbox",
    "indeterminate_check_box",
    "info",
    "info_outline",
    "input",
    "insert_chart",
    "insert_chart_outlined",
    "insert_comment",
    "insert_drive_file",
    "insert_emoticon",
    "insert_invitation",
    "insert_link",
    "insert_photo",
    "insights",
    "integration_instructions",
    "inventory",
    "inventory_2",
    "invert_colors",
    "invert_colors_off",
    "invert_colors_on",
    "ios_share",
    "iso",
    "kayaking",
    "keyboard",
    "keyboard_arrow_down",
    "keyboard_arrow_left",
    "keyboard_arrow_right",
    "keyboard_arrow_up",
    "keyboard_backspace",
    "keyboard_capslock",
    "keyboard_hide",
    "keyboard_return",
    "keyboard_tab",
    "keyboard_voice",
    "king_bed",
    "kitchen",
    "kitesurfing",
    "label",
    "label_important",
    "label_important_outline",
    "label_off",
    "label_outline",
    "landscape",
    "language",
    "laptop",
    "laptop_chromebook",
    "laptop_mac",
    "laptop_windows",
    "last_page",
    "launch",
    "layers",
    "layers_clear",
    "leaderboard",
    "leak_add",
    "leak_remove",
    "leave_bags_at_home",
    "legend_toggle",
    "lens",
    "library_add",
    "library_add_check",
    "library_books",
    "library_music",
    "light",
    "light_mode",
    "lightbulb",
    "lightbulb_outline",
    "line_style",
    "line_weight",
    "linear_scale",
    "link",
    "link_off",
    "linked_camera",
    "liquor",
    "list",
    "list_alt",
    "live_help",
    "live_tv",
    "local_activity",
    "local_airport",
    "local_atm",
    "local_attraction",
    "local_bar",
    "local_cafe",
    "local_car_wash",
    "local_convenience_store",
    "local_dining",
    "local_drink",
    "local_fire_department",
    "local_florist",
    "local_gas_station",
    "local_grocery_store",
    "local_hospital",
    "local_hotel",
    "local_laundry_service",
    "local_library",
    "local_mall",
    "local_movies",
    "local_offer",
    "local_parking",
    "local_pharmacy",
    "local_phone",
    "local_pizza",
    "local_play",
    "local_police",
    "local_post_office",
    "local_printshop",
    "local_see",
    "local_shipping",
    "local_taxi",
    "location_city",
    "location_disabled",
    "location_history",
    "location_off",
    "location_on",
    "location_pin",
    "location_searching",
    "lock",
    "lock_clock",
    "lock_open",
    "lock_outline",
    "login",
    "logout",
    "looks",
    "looks_3",
    "looks_4",
    "looks_5",
    "looks_6",
    "looks_one",
    "looks_two",
    "loop",
    "loupe",
    "low_priority",
    "loyalty",
    "lte_mobiledata",
    "lte_plus_mobiledata",
    "luggage",
    "lunch_dining",
    "mail",
    "mail_outline",
    "map",
    "maps_home_work",
    "maps_ugc",
    "margin",
    "mark_as_unread",
    "mark_chat_read",
    "mark_chat_unread",
    "mark_email_read",
    "mark_email_unread",
    "markunread",
    "markunread_mailbox",
    "masks",
    "maximize",
    "mediation",
    "medical_services",
    "medication",
    "meeting_room",
    "memory",
    "menu",
    "menu_book",
    "menu_open",
    "merge_type",
    "message",
    "messenger",
    "messenger_outline",
    "mic",
    "mic_external_off",
    "mic_external_on",
    "mic_none",
    "mic_off",
    "microwave",
    "military_tech",
    "minimize",
    "miscellaneous_services",
    "missed_video_call",
    "mms",
    "mobile_friendly",
    "mobile_off",
    "mobile_screen_share",
    "mode",
    "mode_comment",
    "mode_edit",
    "model_training",
    "monetization_on",
    "money",
    "money_off",
    "monitor",
    "monochrome_photos",
    "mood",
    "mood_bad",
    "moped",
    "more",
    "more_horiz",
    "more_time",
    "more_vert",
    "motion_photos_auto",
    "motion_photos_off",
    "motion_photos_on",
    "motion_photos_pause",
    "motion_photos_paused",
    "motorcycle",
    "mouse",
    "move_to_inbox",
    "movie",
    "movie_creation",
    "movie_filter",
    "mp",
    "multiline_chart",
    "multiple_stop",
    "museum",
    "music_note",
    "music_off",
    "music_video",
    "my_library_add",
    "my_library_books",
    "my_library_music",
    "my_location",
    "nat",
    "nature",
    "nature_people",
    "navigate_before",
    "navigate_next",
    "navigation",
    "near_me",
    "near_me_disabled",
    "nearby_error",
    "nearby_off",
    "network_cell",
    "network_check",
    "network_locked",
    "network_wifi",
    "new_releases",
    "next_plan",
    "next_week",
    "nfc",
    "night_shelter",
    "nightlife",
    "nightlight",
    "nightlight_round",
    "nightlight_rounded",
    "nightlight_round_outlined",
    "nightlight_round_sharp",
    "nightlight_sharp",
    "nights_stay",
    "no_accounts",
    "no_backpack",
    "no_cell",
    "no_drinks",
    "no_encryption",
    "no_flash",
    "no_food",
    "no_luggage",
    "no_meals",
    "no_meals_ouline",
    "no_meeting_room",
    "no_photography",
    "no_sim",
    "no_stroller",
    "no_transfer",
    "north",
    "north_east",
    "north_west",
    "not_accessible",
    "not_interested",
    "not_listed_location",
    "not_started",
    "note",
    "note_add",
    "notes",
    "notification_add",
    "notification_important",
    "notifications",
    "notifications_active",
    "notifications_none",
    "notifications_off",
    "notifications_paused",
    "offline_bolt",
    "offline_pin",
    "offline_share",
    "ondemand_video",
    "online_prediction",
    "opacity",
    "open_in_browser",
    "open_in_full",
    "open_in_new",
    "open_with",
    "outbond",
    "outbound",
    "outbox",
    "outdoor_grill",
    "outgoing_mail",
    "outlet",
    "outlined_flag",
    "padding",
    "pages",
    "pageview",
    "palette",
    "pan_tool",
    "panorama",
    "panorama_fish_eye",
    "panorama_horizontal",
    "panorama_vertical",
    "panorama_wide_angle",
    "panorama_wide_angle_select",
    "paragliding",
    "park",
    "party_mode",
    "password",
    "pattern",
    "pause",
    "pause_circle",
    "pause_circle_filled",
    "pause_circle_outline",
    "pause_presentation",
    "payment",
    "payments",
    "pedal_bike",
    "pending",
    "pending_actions",
    "people",
    "people_alt",
    "people_outline",
    "perm_camera_mic",
    "perm_contact_cal",
    "perm_contact_calendar",
    "perm_data_setting",
    "perm_device_info",
    "perm_device_information",
    "perm_identity",
    "perm_media",
    "perm_phone_msg",
    "perm_scan_wifi",
    "person",
    "person_add",
    "person_add_alt",
    "person_add_alt_1",
    "person_add_disabled",
    "person_off",
    "person_outline",
    "person_pin",
    "person_pin_circle",
    "person_remove",
    "person_remove_alt_1",
    "person_search",
    "personal_injury",
    "personal_video",
    "pest_control",
    "pest_control_rodent",
    "pets",
    "phone",
    "phone_android",
    "phone_bluetooth_speaker",
    "phone_callback",
    "phone_disabled",
    "phone_enabled",
    "phone_forwarded",
    "phone_in_talk",
    "phone_iphone",
    "phone_locked",
    "phone_missed",
    "phone_paused",
    "phonelink",
    "phonelink_erase",
    "phonelink_lock",
    "phonelink_off",
    "phonelink_ring",
    "phonelink_setup",
    "photo",
    "photo_album",
    "photo_camera",
    "photo_camera_back",
    "photo_camera_front",
    "photo_filter",
    "photo_library",
    "photo_size_select_actual",
    "photo_size_select_large",
    "photo_size_select_small",
    "picture_as_pdf",
    "picture_in_picture",
    "picture_in_picture_alt",
    "pie_chart",
    "pie_chart_outline",
    "pin",
    "pin_drop",
    "pivot_table_chart",
    "place",
    "plagiarism",
    "play_arrow",
    "play_circle",
    "play_circle_fill",
    "play_circle_filled",
    "play_circle_outline",
    "play_disabled",
    "play_for_work",
    "play_lesson",
    "playlist_add",
    "playlist_add_check",
    "playlist_play",
    "plumbing",
    "plus_one",
    "podcasts",
    "point_of_sale",
    "policy",
    "poll",
    "polymer",
    "pool",
    "portable_wifi_off",
    "portrait",
    "post_add",
    "power",
    "power_input",
    "power_off",
    "power_settings_new",
    "precision_manufacturing",
    "pregnant_woman",
    "present_to_all",
    "preview",
    "print",
    "print_disabled",
    "priority_high",
    "privacy_tip",
    "private_connectivity",
    "production_quantity_limits",
    "psychology",
    "public",
    "public_off",
    "publish",
    "published_with_changes",
    "push_pin",
    "qr_code",
    "qr_code_2",
    "qr_code_scanner",
    "query_builder",
    "question_answer",
    "queue",
    "queue_music",
    "queue_play_next",
    "quick_contacts_dialer",
    "quick_contacts_mail",
    "quickreply",
    "quiz",
    "radar",
    "radio",
    "radio_button_checked",
    "radio_button_unchecked",
    "railway_alert",
    "ramen_dining",
    "rate_review",
    "raw_off",
    "raw_on",
    "read_more",
    "real_estate_agent",
    "receipt",
    "receipt_long",
    "recent_actors",
    "recommend",
    "record_voice_over",
    "redeem",
    "redo",
    "reduce_capacity",
    "refresh",
    "remove",
    "remove_circle",
    "remove_circle_outline",
    "remove_done",
    "remove_from_queue",
    "remove_moderator",
    "remove_red_eye",
    "remove_shopping_cart",
    "remove_sticky_note",
    "remove_subscription",
    "reorder",
    "repeat",
    "repeat_on",
    "repeat_one",
    "repeat_one_on",
    "replay",
    "replay_10",
    "replay_30",
    "replay_5",
    "replay_circle_filled",
    "reply",
    "reply_all",
    "report",
    "report_gmailerrorred",
    "report_off",
    "report_outlined",
    "report_problem",
    "request_page",
    "request_quote",
    "reset_tv",
    "restaurant",
    "restaurant_menu",
    "restore",
    "restore_from_trash",
    "restore_page",
    "reviews",
    "rice_bowl",
    "ring_volume",
    "roofing",
    "room",
    "room_preferences",
    "room_service",
    "rotate_90_degrees_ccw",
    "rotate_left",
    "rotate_right",
    "rounded_corner",
    "router",
    "rowing",
    "rss_feed",
    "rtt",
    "rule",
    "rule_folder",
    "run_circle",
    "running_with_errors",
    "rv_hookup",
    "safety_divider",
    "sailing",
    "sanitizer",
    "satellite",
    "save",
    "save_alt",
    "saved_search",
    "scanner",
    "scatter_plot",
    "schedule",
    "schedule_send",
    "schema",
    "school",
    "science",
    "score",
    "screen_lock_landscape",
    "screen_lock_portrait",
    "screen_lock_rotation",
    "screen_rotation",
    "screen_search_desktop",
    "screen_share",
    "screenshot",
    "sd",
    "sd_card",
    "sd_card_alert",
    "sd_storage",
    "search",
    "search_off",
    "security",
    "security_update",
    "security_update_good",
    "security_update_warning",
    "segment",
    "select_all",
    "self_improvement",
    "send",
    "send_and_archive",
    "send_to_mobile",
    "sensor_door",
    "sensor_window",
    "sensors",
    "sensors_off",
    "sentiment_dissatisfied",
    "sentiment_neutral",
    "sentiment_satisfied",
    "sentiment_satisfied_alt",
    "sentiment_very_dissatisfied",
    "sentiment_very_satisfied",
    "set_meal",
    "settings",
    "settings_accessibility",
    "settings_applications",
    "settings_backup_restore",
    "settings_bluetooth",
    "settings_brightness",
    "settings_cell",
    "settings_display",
    "settings_ethernet",
    "settings_input_antenna",
    "settings_input_component",
    "settings_input_composite",
    "settings_input_hdmi",
    "settings_input_svideo",
    "settings_overscan",
    "settings_phone",
    "settings_power",
    "settings_remote",
    "settings_suggest",
    "settings_system_daydream",
    "settings_voice",
    "share",
    "share_location",
    "shield",
    "shop",
    "shop_two",
    "shopping_bag",
    "shopping_basket",
    "shopping_cart",
    "short_text",
    "show_chart",
    "shuffle",
    "shuffle_on",
    "shutter_speed",
    "sick",
    "signal_cellular_0_bar",
    "signal_cellular_4_bar",
    "signal_cellular_alt",
    "signal_cellular_connected_no_internet_0_bar",
    "signal_cellular_connected_no_internet_4_bar",
    "signal_cellular_no_sim",
    "signal_cellular_null",
    "signal_cellular_off",
    "signal_wifi_0_bar",
    "signal_wifi_4_bar",
    "signal_wifi_4_bar_lock",
    "signal_wifi_bad",
    "signal_wifi_connected_no_internet_4",
    "signal_wifi_off",
    "sim_card",
    "sim_card_alert",
    "single_bed",
    "single_bed_alt",
    "single_bed_outlined",
    "6_ft_apart",
    "skateboarding",
    "skip_next",
    "skip_previous",
    "sledding",
    "slideshow",
    "slow_motion_video",
    "smart_button",
    "smart_display",
    "smart_screen",
    "smart_toy",
    "smartphone",
    "smoke_free",
    "smoking_rooms",
    "sms",
    "sms_failed",
    "snippet_folder",
    "snooze",
    "snowboarding",
    "snowmobile",
    "snowshoeing",
    "soap",
    "social_distance",
    "sort",
    "sort_by_alpha",
    "source",
    "south",
    "south_east",
    "south_west",
    "spa",
    "space_dashboard",
    "speaker",
    "speaker_group",
    "speaker_notes",
    "speaker_notes_off",
    "speaker_phone",
    "speed",
    "spellcheck",
    "splitscreen",
    "sports",
    "sports_bar",
    "sports_baseball",
    "sports_basketball",
    "sports_cricket",
    "sports_esports",
    "sports_football",
    "sports_golf",
    "sports_handball",
    "sports_hockey",
    "sports_kabaddi",
    "sports_mma",
    "sports_motorsports",
    "sports_rugby",
    "sports_soccer",
    "sports_tennis",
    "sports_volleyball",
    "square_foot",
    "stacked_bar_chart",
    "stacked_line_chart",
    "stairs",
    "star",
    "star_border",
    "star_border_purple500",
    "star_half",
    "star_outline",
    "star_purple500",
    "star_rate",
    "stars",
    "stay_current_landscape",
    "stay_current_portrait",
    "stay_primary_landscape",
    "stay_primary_portrait",
    "sticky_note_2",
    "stop",
    "stop_circle",
    "stop_screen_share",
    "storage",
    "store",
    "store_mall_directory",
    "storefront",
    "storm",
    "straighten",
    "stream",
    "streetview",
    "strikethrough_s",
    "stroller",
    "style",
    "subdirectory_arrow_left",
    "subdirectory_arrow_right",
    "subject",
    "subscript",
    "subscript_off",
    "subscriptions",
    "subtitles",
    "subtitles_off",
    "subway",
    "summarize",
    "superscript",
    "supervised_user_circle",
    "supervisor_account",
    "support",
    "support_agent",
    "support_outlined",
    "support_rounded",
    "support_sharp",
    "surfing",
    "surround_sound",
    "swap_calls",
    "swap_horiz",
    "swap_horizontal_circle",
    "swap_vert",
    "swap_vert_circle",
    "swap_vertical_circle",
    "swipe",
    "switch_account",
    "switch_camera",
    "switch_left",
    "switch_right",
    "switch_video",
    "sync",
    "sync_alt",
    "sync_disabled",
    "sync_problem",
    "sync_rounded",
    "sync_sharp",
    "system_security_update",
    "system_security_update_good",
    "system_security_update_warning",
    "system_update",
    "system_update_alt",
    "system_update_tv",
    "tab",
    "tab_unselected",
    "table_chart",
    "table_rows",
    "table_view",
    "tablet",
    "tablet_android",
    "tablet_mac",
    "tag",
    "tag_faces",
    "takeout_dining",
    "tap_and_play",
    "tapas",
    "task",
    "task_alt",
    "taxi_alert",
    "terrain",
    "text_fields",
    "text_format",
    "text_rotate_up",
    "text_rotate_vertical",
    "text_rotation_angledown",
    "text_rotation_angleup",
    "text_rotation_down",
    "text_rotation_none",
    "text_snippet",
    "textsms",
    "texture",
    "theater_comedy",
    "theaters",
    "thermostat",
    "thermostat_auto",
    "thumb_down",
    "thumb_down_alt",
    "thumb_down_off_alt",
    "thumb_up",
    "thumb_up_alt",
    "thumb_up_off_alt",
    "thumbs_up_down",
    "time_to_leave",
    "timelapse",
    "timeline",
    "timer",
    "timer_10",
    "timer_10_select",
    "timer_3",
    "timer_3_select",
    "timer_off",
    "tips_and_updates",
    "title",
    "toc",
    "today",
    "toggle_off",
    "toggle_on",
    "toll",
    "tonality",
    "topic",
    "touch_app",
    "tour",
    "toys",
    "track_changes",
    "traffic",
    "train",
    "tram",
    "transfer_within_a_station",
    "transform",
    "transgender",
    "transit_enterexit",
    "translate",
    "travel_explore",
    "trending_down",
    "trending_flat",
    "trending_neutral",
    "trending_up",
    "trip_origin",
    "try",
    "tty",
    "tune",
    "tungsten",
    "turned_in",
    "turned_in_not",
    "tv",
    "tv_off",
    "two_wheeler",
    "umbrella",
    "unarchive",
    "undo",
    "unfold_less",
    "unfold_more",
    "unpublished",
    "unsubscribe",
    "upcoming",
    "update",
    "update_disabled",
    "upgrade",
    "upload",
    "upload_file",
    "usb",
    "usb_off",
    "verified",
    "verified_user",
    "vertical_align_bottom",
    "vertical_align_center",
    "vertical_align_top",
    "vertical_distribute",
    "vertical_split",
    "vibration",
    "video_call",
    "video_camera_back",
    "video_camera_front",
    "video_collection",
    "video_label",
    "video_library",
    "video_settings",
    "video_stable",
    "videocam",
    "videocam_off",
    "videogame_asset",
    "view_agenda",
    "view_array",
    "view_carousel",
    "view_column",
    "view_comfortable",
    "view_comfy",
    "view_compact",
    "view_day",
    "view_headline",
    "view_in_ar",
    "view_list",
    "view_module",
    "view_quilt",
    "view_sidebar",
    "view_stream",
    "view_column_2",
    "view_week",
    "vignette",
    "villa",
    "visibility",
    "visibility_off",
    "voice_chat",
    "voice_over_off",
    "voicemail",
    "volume_down",
    "volume_mute",
    "volume_off",
    "volume_up",
    "volunteer_activism",
    "vpn_key",
    "vpn_lock",
    "vrpano",
    "wallet_giftcard",
    "wallet_membership",
    "wallet_travel",
    "wallpaper",
    "warning",
    "warning_amber",
    "wash",
    "watch",
    "watch_later",
    "water",
    "water_damage",
    "water_drop",
    "waterfall_chart",
    "waves",
    "wb_auto",
    "wb_cloudy",
    "wb_incandescent",
    "wb_iridescent",
    "wb_shade",
    "wb_sunny",
    "wb_twilight",
    "wc",
    "web",
    "web_asset",
    "web_stories",
    "weekend",
    "west",
    "whatshot",
    "wheelchair_pickup",
    "where_to_vote",
    "widgets",
    "wifi",
    "wifi_calling",
    "wifi_calling_3",
    "wifi_calling_4",
    "wifi_lock",
    "wifi_off",
    "wifi_protected_setup",
    "wifi_tethering",
    "wine_bar",
    "work",
    "work_off",
    "work_outline",
    "workspaces",
    "wrap_text",
    "wrong_location",
    "wysiwyg",
    "youtube_searched_for",
    "zoom_in",
    "zoom_out",
    "zoom_out_map",
  ]

  constructor(
    private dialogRef: DialogRef<any>,
    @Inject(DIALOG_DATA) public data: string,
  ) { }

  ngOnInit(): void {
    this.allIcons = this.hytIconList.concat(this.faIconList).concat(this.matIconList);
    this.selectedIcon = this.data;
    this.filterIconList();
  }

  filterIconList() {
    this.filteredIcons = this.allIcons.filter(icon => icon.includes(this.filterValue));
  }

  onIconSelected(icon) {
    this.selectedIcon = icon;
    this.dismissModal(icon);
  }

  deselectIcon() {
    this.selectedIcon = '';
    this.dismissModal('');
  }

  dismissModal(result: string) {
    this.dialogRef.close(result);
  }


  close() {
    this.dialogRef.close(this.selectedIcon);
  }

  isMaterialIcon(icon: string): boolean {
    return this.matIconList.includes(icon);
  }
}
