export * from './alarms.service';
import { AlarmsService } from './alarms.service';
export * from './alarmsEvents.service';
import { AlarmsEventsService } from './alarmsEvents.service';
export * from './algorithm.service';
import { AlgorithmService } from './algorithm.service';
export * from './area_.service';
import { Area_Service } from './area_.service';
export * from './assetCategories.service';
import { AssetCategoriesService } from './assetCategories.service';
export * from './assetTags.service';
import { AssetTagsService } from './assetTags.service';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './company.service';
import { CompanyService } from './company.service';
export * from './dashboardWidgets.service';
import { DashboardWidgetsService } from './dashboardWidgets.service';
export * from './dashboards.service';
import { DashboardsService } from './dashboards.service';
export * from './diagnoseType.service';
import { DiagnoseTypeService } from './diagnoseType.service';
export * from './hBaseConnector.service';
import { HBaseConnectorService } from './hBaseConnector.service';
export * from './hDevices.service';
import { HDevicesService } from './hDevices.service';
export * from './hPacket.service';
import { HPacketService } from './hPacket.service';
export * from './hProject.service';
import { HProjectService } from './hProject.service';
export * from './hProjectAlgorithms.service';
import { HProjectAlgorithmsService } from './hProjectAlgorithms.service';
export * from './hUser.service';
import { HUserService } from './hUser.service';
export * from './kafkaConnector.service';
import { KafkaConnectorService } from './kafkaConnector.service';
export * from './kit.service';
import { KitService } from './kit.service';
export * from './mailTemplates.service';
import { MailTemplatesService } from './mailTemplates.service';
export * from './permissions.service';
import { PermissionsService } from './permissions.service';
export * from './ruleEngine.service';
import { RuleEngineService } from './ruleEngine.service';
export * from './services.service';
import { ServicesService } from './services.service';
export * from './sharedEntity.service';
import { SharedEntityService } from './sharedEntity.service';
export * from './sparkManager.service';
import { SparkManagerService } from './sparkManager.service';
export * from './storm.service';
import { StormService } from './storm.service';
export * from './uIBranding.service';
import { UIBrandingService } from './uIBranding.service';
export * from './widgets.service';
import { WidgetsService } from './widgets.service';
export * from './zookeeperConnector.service';
import { ZookeeperConnectorService } from './zookeeperConnector.service';
export const APIS = [AlarmsService, AlarmsEventsService, AlgorithmService, Area_Service, AssetCategoriesService, AssetTagsService, AuthenticationService, CompanyService, DashboardWidgetsService, DashboardsService, DiagnoseTypeService, HBaseConnectorService, HDevicesService, HPacketService, HProjectService, HProjectAlgorithmsService, HUserService, KafkaConnectorService, KitService, MailTemplatesService, PermissionsService, RuleEngineService, ServicesService, SharedEntityService, SparkManagerService, StormService, UIBrandingService, WidgetsService, ZookeeperConnectorService];
